### ISSUE TITLE
复制pdf内换行的文字会重字

### ISSUE THREAD

**Issue by temporalu** [CopyPlusPlus/CopyPlusPlus-NetFramework#53]
如图。pdf软件为pdf xchange editor
![图片](https://github.com/CopyPlusPlus/CopyPlusPlus/assets/122422616/dd7a0bab-b1e7-4fa6-870f-581bd030d0f8)

**Comment by temporalu** [comment]
配置如图。
![图片](https://github.com/CopyPlusPlus/CopyPlusPlus/assets/122422616/227a7b6d-57f6-459c-8a32-0662824b7e9b)

**Comment by temporalu** [comment]
关闭合并换行后仍然存在。
![图片](https://github.com/CopyPlusPlus/CopyPlusPlus/assets/122422616/fab12d05-1957-4752-8c2a-85210e881a9a)

**Comment by temporalu** [comment]
抱歉，好像是pdf的问题，不是软件问题。

**Comment by wy-luke** [comment]
@WinfredLu 问题不大
