### ISSUE TITLE
MAC端软件？

### ISSUE THREAD

**Issue by H-CunKang** [CopyPlusPlus/CopyPlusPlus-NetFramework#55]
没有苹果电脑用的软件吗？给了代码，苹果电脑可以直接用代码吗？如何实现？

**Comment by wy-luke** [comment]
代码不可以直接用，Mac 版本的项目在这里：https://github.com/CopyPlusPlus/CopyPlusPlus-Qt，

目前开发还没完成，可以先试下测试版本：[CopyPlusPlus-macOS.zip](https://github.com/CopyPlusPlus/CopyPlusPlus/files/13643311/CopyPlusPlus-macOS.zip)
